### ISSUE TITLE
Ensure that the analysis model is correct

### ISSUE THREAD

**Issue by EmmKirHan** [JacobMoller/BDSAProject#52]

**Comment by Werenfeldt** [comment]
Vi har ændret i MyProjectPage use case da den nu gælder for både Student og Supervisor. 

Skal den deles op i flere use cases således at der er en MyProjectPage, og to use cases som extender denne: StudenMyProjectPage og SupervisorMyProjectPage. 

MyProjectPage use case: 
 User is on the index page and clicks MyProjects
                The System presents a list of all Projects, from the database, 

SupervisorProjectPage:
Using the MyProjectPage use case. 

The System returns projects that are either created by the Supervisor, 

StudentProjectPage:
Using the MyProjectPage use case. 

The system returns projects applied for by the Student.

**Comment by Werenfeldt** [comment]
Scenarie SupervisorCancelProject. 

Vi beskriver ikke en cancel button. Så skal vi omformulere vores use case om DeleteProject - så hvis der er students som har applied så bliver projected ikke deleted, men closed i stedet.

**Comment by Werenfeldt** [comment]
Scenarie CreateProject: 

Her beskriver vi notifikationer og ikke auto accept. What to do?

**Comment by Werenfeldt** [comment]
Figure 8 - sequence diagram skal ændres: User i stedet for Supervisor.

**Comment by Werenfeldt** [comment]
Figure 9 - CRC kort skal ændres på MyProjectPage: User i stedet for Supervisor

**Comment by Werenfeldt** [comment]
Control Objects: MyProjects??? ikke et verb? Hvad er dette for et control object?

**Comment by Werenfeldt** [comment]
Error cases: 
ValidateError case - Response(CreatedProject, UpdatedProject)
LostConnect case - Alle Responses
